from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from .metrics import mean_pairwise_cosine_distance, mean_pairwise_hamming, pairwise_state_jsd, percentile_ci


METRICS = [
    "mean_accuracy",
    "robust_accuracy",
    "wording_disagreement",
    "seed_disagreement",
    "semantic_jsd",
    "valid_diversity",
]


def load_embeddings(path: Path | None) -> dict[str, np.ndarray]:
    if path is None or not path.exists():
        return {}
    archive = np.load(path)
    return {str(key): value for key, value in zip(archive["paths"], archive["embeddings"])}


def case_metrics(group: pd.DataFrame, embeddings: dict[str, np.ndarray]) -> dict[str, float | str]:
    variants = sorted(group["variant_id"].unique())
    seeds = sorted(group["seed"].unique())
    expected = len(variants) * len(seeds)
    if len(group) != expected or group.duplicated(["variant_id", "seed"]).any():
        raise ValueError(f"Incomplete grid for {group.iloc[0]['model']}/{group.iloc[0]['case_id']}: {len(group)} != {expected}")

    wording = []
    for _, seed_group in group.groupby("seed"):
        wording.append(mean_pairwise_hamming(seed_group.sort_values("variant_id")["semantic_state"].tolist()))
    seed_variation = []
    for _, prompt_group in group.groupby("variant_id"):
        seed_variation.append(mean_pairwise_hamming(prompt_group.sort_values("seed")["semantic_state"].tolist()))
    state_groups = [
        prompt_group.sort_values("seed")["semantic_state"].tolist()
        for _, prompt_group in group.groupby("variant_id")
    ]

    diversity_groups = []
    eligible_pairs = 0
    for _, prompt_group in group.groupby("variant_id"):
        valid_paths = prompt_group.loc[prompt_group["all_correct"] == 1, "image_path"].astype(str).tolist()
        vectors = [embeddings[path] for path in valid_paths if path in embeddings]
        if len(vectors) >= 2:
            eligible_pairs += len(vectors) * (len(vectors) - 1) // 2
            diversity_groups.append(mean_pairwise_cosine_distance(np.stack(vectors)))

    return {
        "model": str(group.iloc[0]["model"]),
        "case_id": str(group.iloc[0]["case_id"]),
        "category": str(group.iloc[0]["category"]),
        "mean_accuracy": float(group["all_correct"].mean()),
        "robust_accuracy": float(group.groupby("variant_id")["all_correct"].mean().min()),
        "wording_disagreement": float(np.nanmean(wording)),
        "seed_disagreement": float(np.nanmean(seed_variation)),
        "semantic_jsd": pairwise_state_jsd(state_groups),
        "valid_diversity": float(np.nanmean(diversity_groups)) if diversity_groups else np.nan,
        "valid_diversity_pairs": eligible_pairs,
    }


def latex_table(summary: pd.DataFrame) -> str:
    rows = []
    for model, group in summary[summary["category"] == "all"].groupby("model"):
        by_metric = group.set_index("metric")
        values = []
        for metric in METRICS:
            row = by_metric.loc[metric]
            values.append(f"{row['estimate']:.3f} [{row['ci_low']:.3f}, {row['ci_high']:.3f}]")
        safe_model = str(model).replace("_", "\\_")
        rows.append(safe_model + " & " + " & ".join(values) + r" \\")
    if not rows:
        return "% No results found.\n"
    return "\n".join([
        "% Auto-generated by python -m paraseedbench.analyze",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r"Model & Mean$\uparrow$ & Robust$\uparrow$ & Word$\downarrow$ & Seed$\downarrow$ & JSD$\downarrow$ & Div.$\uparrow$ \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ])


def plot_category_robustness(summary: pd.DataFrame, output_dir: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    data = summary[(summary["metric"] == "robust_accuracy") & (summary["category"] != "all")]
    if data.empty:
        return
    pivot = data.pivot(index="category", columns="model", values="estimate")
    ax = pivot.plot(kind="bar", figsize=(7.0, 3.4), width=0.78)
    ax.set_ylabel("Robust accuracy")
    ax.set_xlabel("")
    ax.set_ylim(0, 1)
    ax.grid(axis="y", alpha=0.25)
    ax.legend(title="Model", frameon=False, ncol=max(1, min(3, len(pivot.columns))))
    plt.xticks(rotation=20, ha="right")
    plt.tight_layout()
    plt.savefig(output_dir / "category_robust_accuracy.pdf", bbox_inches="tight")
    plt.savefig(output_dir / "category_robust_accuracy.png", dpi=200, bbox_inches="tight")
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze the factorized semantic outcome grid")
    parser.add_argument("--scores", required=True)
    parser.add_argument("--embeddings", default=None)
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--bootstrap", type=int, default=2000)
    parser.add_argument("--bootstrap-seed", type=int, default=2027)
    parser.add_argument("--paper-table", default=None)
    args = parser.parse_args()

    score_path = Path(args.scores)
    output_dir = Path(args.output_dir) if args.output_dir else score_path.parent / "analysis"
    output_dir.mkdir(parents=True, exist_ok=True)
    data = pd.read_csv(score_path, dtype={"semantic_state": str})
    data = data[data["kind"] == "equivalent"].copy()
    if data.empty:
        raise ValueError("No equivalent-prompt rows found")
    embeddings = load_embeddings(Path(args.embeddings) if args.embeddings else None)

    cases = pd.DataFrame([
        case_metrics(group, embeddings)
        for _, group in data.groupby(["model", "case_id"], sort=True)
    ])
    cases.to_csv(output_dir / "case_metrics.csv", index=False)

    rng = np.random.default_rng(args.bootstrap_seed)
    summary_rows = []
    for model, model_group in cases.groupby("model"):
        for category in ["all", *sorted(model_group["category"].unique())]:
            subset = model_group if category == "all" else model_group[model_group["category"] == category]
            for metric in METRICS:
                values = subset[metric].to_numpy(dtype=float)
                finite = values[np.isfinite(values)]
                estimate = float(np.mean(finite)) if len(finite) else np.nan
                low, high = percentile_ci(finite, rng, args.bootstrap)
                summary_rows.append({
                    "model": model, "category": category, "metric": metric,
                    "estimate": estimate, "ci_low": low, "ci_high": high,
                    "n_scenes": len(subset), "n_finite": len(finite),
                })
    summary = pd.DataFrame(summary_rows)
    summary.to_csv(output_dir / "summary.csv", index=False)
    plot_category_robustness(summary, output_dir)

    pairwise_rows = []
    models = sorted(cases["model"].unique())
    for left_index, left in enumerate(models):
        for right in models[left_index + 1 :]:
            paired = cases[cases["model"] == left].merge(
                cases[cases["model"] == right], on="case_id", suffixes=("_left", "_right")
            )
            for metric in METRICS:
                delta = paired[f"{metric}_left"].to_numpy(float) - paired[f"{metric}_right"].to_numpy(float)
                finite = delta[np.isfinite(delta)]
                low, high = percentile_ci(finite, rng, args.bootstrap)
                pairwise_rows.append({
                    "left": left, "right": right, "metric": metric,
                    "delta_left_minus_right": float(np.mean(finite)) if len(finite) else np.nan,
                    "ci_low": low, "ci_high": high, "n_scenes": len(finite),
                })
    pd.DataFrame(pairwise_rows).to_csv(output_dir / "paired_model_differences.csv", index=False)

    table = latex_table(summary)
    (output_dir / "results_table.tex").write_text(table, encoding="utf-8")
    if args.paper_table:
        paper_path = Path(args.paper_table)
        paper_path.parent.mkdir(parents=True, exist_ok=True)
        paper_path.write_text(table, encoding="utf-8")
    print(f"Analysis written to {output_dir}")


if __name__ == "__main__":
    main()
